# Generated by Django 3.2.6 on 2021-08-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
