# Generated by Django 3.2.6 on 2021-08-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayCakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('offer', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cake_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_api.cakevariety')),
            ],
        ),
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('delivered_by', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('cake_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_api.displaycakes')),
            ],
        ),
    ]
