# Generated by Django 3.2.6 on 2021-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_api', '0002_auto_20210816_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
